### ISSUE TITLE
Http Interface Routes - Pre-defined Map or Registering routes on the go

### ISSUE THREAD

**Issue by jhkuperus** [KrekkieD/nocca#1]
I was refactoring the webserver.js file to remove the switch on the route. I found there to be two approaches to increase maintainability. One is using a map that refers to functions:

```javascript
var routes = {
  'POST:/caches': addCaches,
  'GET:/caches': getCaches
};
```

This creates a sort of automatic documentation of the available endpoints, but makes it harder to see under which request path a function is mapped when editing that functoin more down the file.

The other option is registering routes using functions:

```javascript
var routes = {};

route(r, handler) { routes[r] = handler }

route('POST:/caches', function(req, res, config) { ... });
route('GET:/caches', funciton(req, res, config) { ... });
```

This makes it harder to see all supported endpoints, but makes it easier to see which URL(s) a function is reachable under.

Which one would you prefer? :) I've refactored it to the second one now, you can take a look at it at the develop branch src/node/lib_v2/httpInterface

**Comment by KrekkieD** [comment]
Changed to a hybrid of both -- using an addRoute function with string + named function. All routes are up top for a concise endpoint overview. Functions should be named in a way that makes it easy to determine what it does and will return. This should take care of readability of endpoints.

	// Configure routes
	addRoute('GET:/caches', getCaches);
	addRoute('POST:/caches/package', addCachePackage);
	addRoute('GET:/enums/scenarios/type', getEnumScenariosType);
	addRoute('GET:/enums/scenarios/repeatable', getEnumScenariosRepeatable);
	addRoute('POST:/scenarios/startRecording', startRecordingScenario);
	addRoute('POST:/scenarios/finishRecording', stopRecordingScenario);
	addRoute('GET:/scenarios/:scenarioKey', true, getScenarioByKey);
	addRoute('GET:/scenarios/:scenarioKey/active', true, getScenarioStatusByKey);

Mapping a function back to one or multiple endpoints is less simple and will require searching for usages of that function in the addRoute section. Wonder how often that is required though :)
