### ISSUE TITLE
Support xpath keyGenerator

### ISSUE THREAD

**Issue by jhkuperus** [KrekkieD/nocca#14]

**Comment by KrekkieD** [comment]
Providing this generator out of the box so it can be used without having the consumer write it themselves?

**Comment by jhkuperus** [comment]
Yeah. It would make sense to have it provided, just to support XML documents. Although most things can probably be done with regeces as well.

**Comment by KrekkieD** [comment]
Included in PR for cherryPickingKeygen plugin. Xpath part should be tested.

**Comment by KrekkieD** [comment]
verified
