### ISSUE TITLE
complete REST endpoints for managing single cache entries

### ISSUE THREAD

**Issue by jhkuperus** [KrekkieD/nocca#18]

**Comment by KrekkieD** [comment]
Please elaborate

**Comment by jhkuperus** [comment]
CREATE, DELETE, PATCH. I think those will do. This will allow the gui to update single entries.

--JH

**Comment by jhkuperus** [comment]
Also relates to #9

**Comment by reneoud** [comment]
You did all the hard work already ;)
can this feature be merged to master?
