### ISSUE TITLE
add support for adding 'subscenarios'

### ISSUE THREAD

**Issue by jhkuperus** [KrekkieD/nocca#24]
a scenario would benefit from things like this:

```javascript
new Builder()
  .sequentialScenario()
  .on('some initial')
  .then()
  .runSubScenario(new Builder().asynchronousScenario().on().then().on().then().on().then().on().build())
  .then()
  .on('some final')
  .build();
```

This would cause the scenario to require one single initial step and then awaiting the completion of the subscenario, which is async and can be compared to a q.all() method.

**Comment by KrekkieD** [comment]
cacheQueue functionality might make this obsolete
