### ISSUE TITLE
refactor endpoints component to be more general and allow any URL to be forwarded by default

### ISSUE THREAD

**Issue by jhkuperus** [KrekkieD/nocca#25]
Right now an endpoint has to be explicitly configured before anything works. It would be nicer if we supported actually proxying requests. The current behaviour could be refactored as an implementation of that more generic way:

```javascript
endpoints: {
  google: {
    match: Nocca.$endpointMatchers.hostMatcher('google.com'),
    keyGenerator: Nocca.$keyGenerators.urlOnlyKeyGeneratorBuilder()
  },
  ourInternalWebServiceA: {
    match: Nocca.$endpointMatchers.combine(
      Nocca.$endpointMatchers.host('services.internal.us.com'),
      Nocca.$endpointMatchers.urlPrefix('/services/serviceA')
    ),
    keyGenerator: Nocca.$keyGenerators.bodyRegexKeyGeneratorBuilder(/* ... */)
  }
```

**Comment by KrekkieD** [comment]
`endpoints` currently searches for and endpoint with key `_default` as a fallback endpoint. This usually serves as a proxy but might be too generic.
