### ISSUE TITLE
Should be able to run on separate server

### ISSUE THREAD

**Issue by KrekkieD** [KrekkieD/nocca#3]
For loadtesting the mockserver should be able to run on a different server. Running it on the same server means performance could be altered because of the mockserver, which will pollute the loadtest result.

An interesting challenge is how the mocking config could be contained in the app itself but needs to run on a different server. Do you copy the app source to the mocking server and only run the node mock server? Would the mockserver run a clean version of Nocca and then get config fed (i.e. through HTTP) before loadtest begins?

**Comment by jhkuperus** [comment]
I think we should offer both ways. Either start nocca with something like `npm install nocca && nocca myCacheConfig.json`, or use your automated tools to upload and control the nocca instance. We pretty much have a fully functional REST API. I think that should be capable of handling all configuration.

**Comment by KrekkieD** [comment]
Config could go further than just json endpoints (i.e. javascript function overrides). 

I guess uploading config files (any files, js, json) to a dedicated app (temp / cleanable) folder should be possible.

**Comment by jhkuperus** [comment]
Oh yeah right. I keep forgetting JSON won't allow functions :)

Then yeah, I guess we should support a location to allow uploading files to, which will then be required into the app. I would suggest not enabling that feature by default, as it poses quite a risk if it is active on a public nocca ;)

Or is there a sensible way to sandbox a script file?

**Comment by KrekkieD** [comment]
Good point.

**Comment by KrekkieD** [comment]
Probably best to also configure this using the 'plugin' idea we have. Plugins could then carry a name (and maybe a type to indicate what the plugin is?). The JSON object can carry the names of the plugins instead of the actual constructor function as we have in the defaultConfig now. 

Challenge would then still be to get the plugins into the Nocca instance, but at least the configuration part is handled.

**Comment by KrekkieD** [comment]
Plugin implementation is ready, config is moving more and more towards json only. Running on a standalone server and feeding (parts of) configuration is possible.
