### ISSUE TITLE
Share the same Nocca server across apps

### ISSUE THREAD

**Issue by KrekkieD** [KrekkieD/nocca#4]
Currently a single Java Mocking server is hosted on the internal network. This app is fed the config for a specific application. 

Nocca might be able to cater to multiple apps at the same time by listening on certain paths (i.e. configure proxy requests to use a prefix: localhost:3003/APPNAME/endpointname/). This way multiple apps could have an entirely standalone configuration, as long as APPNAME is unique. 

Every APP could share the same server but use different request listeners (should consider performance), or could use different ports (which may altogether remove the need for an APPNAME prefix).

**Comment by jhkuperus** [comment]
I would opt for opening multiple ports. That leaves the most flexibility in configuration from both Nocca and the client applications.

For example, assume you develop locally, run Nocca locally and are not using an APPNAME prefix. Then there are these possible scenarios:
1. You test remotely on a single Nocca instance dedicated to your App -> No need to prefix with APPNAME either way
2. You test remotely on a single Nocca instance shared between Apps -> APPNAME prefix needed if the same port is also used. If different ports are used, you need not change your URLs, just the port you connect to or proxy through
3. You test remotely on multiple Nocca instances -> APPNAME needs to be configured the same on all instances, no typos allowed, or no APPNAME should be used at all.

This would mean a server config would require mapping a config set to a certain port, e.g.:

```javascript
var serverConfig = {
  instances = {
    appName1: {
      port: 3001,
      configuration: '../configs/appName1_serverConfig.json'
    },
    appName2: {
      port: 3002,
      configuration: '../configs/appName2_serverConfig.json'
    }
  }
};
```

We can even allow control of these 'instances' through REST :)

**Comment by KrekkieD** [comment]
Obsolete issue
